services:
  # Servicio de Base de Datos PostgreSQL
  postgres:
    image: postgres:16-alpine
    container_name: discord_postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${DB_DATABASE:-discord_webhook_manager}
      POSTGRES_USER: root      # Usuario cambiado a root
      POSTGRES_PASSWORD: 1234  # Contrase√±a cambiada a 1234
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Servicio de Adminer (Interfaz Visual)
  adminer:
    image: adminer
    container_name: discord_adminer
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: postgres
    depends_on:
      - postgres

volumes:
  postgres_data: